// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4oeEmqgUTBRow6oGQg-lL86WGPxIM08',
    appId: '1:492466770104:web:d4a6d04761ef2fef74a44d',
    messagingSenderId: '492466770104',
    projectId: 'muc-digital-4390a',
    authDomain: 'muc-digital-4390a.firebaseapp.com',
    storageBucket: 'muc-digital-4390a.firebasestorage.app',
    measurementId: 'G-PBL12DDNWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCXcu8stPnoJbMvLlD3eogU_HdlSU63r4',
    appId: '1:492466770104:android:7887933148f4c7c274a44d',
    messagingSenderId: '492466770104',
    projectId: 'muc-digital-4390a',
    storageBucket: 'muc-digital-4390a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqtZYIOAmpgJRtOSZaXxhD1WOBpLDyRo',
    appId: '1:492466770104:ios:e7f436de8ef483f474a44d',
    messagingSenderId: '492466770104',
    projectId: 'muc-digital-4390a',
    storageBucket: 'muc-digital-4390a.firebasestorage.app',
    iosBundleId: 'com.example.mucDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqtZYIOAmpgJRtOSZaXxhD1WOBpLDyRo',
    appId: '1:492466770104:ios:e7f436de8ef483f474a44d',
    messagingSenderId: '492466770104',
    projectId: 'muc-digital-4390a',
    storageBucket: 'muc-digital-4390a.firebasestorage.app',
    iosBundleId: 'com.example.mucDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe4oeEmqgUTBRow6oGQg-lL86WGPxIM08',
    appId: '1:492466770104:web:4705151756e36e4974a44d',
    messagingSenderId: '492466770104',
    projectId: 'muc-digital-4390a',
    authDomain: 'muc-digital-4390a.firebaseapp.com',
    storageBucket: 'muc-digital-4390a.firebasestorage.app',
    measurementId: 'G-CWR1WK96G2',
  );
}
