type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  photoUrl: String
}

type Project @table {
  title: String!
  createdAt: Timestamp!
  description: String
  dueDate: Date
  creator: User!
}

type ProjectMember @table(key: ["project", "member"]) {
  assignedAt: Timestamp!
  role: String
  project: Project!
  member: User!
}

type Task @table {
  title: String!
  status: String!
  createdAt: Timestamp!
  description: String
  dueDate: Date
  project: Project!
  creator: User!
  assignedTo: User
}

type Comment @table {
  content: String!
  createdAt: Timestamp!
  task: Task!
  author: User!
}